project 'Assign01_LoadingView.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assign01_LoadingView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assign01_LoadingView
  pod 'DynamicColor', '~> 4.0.2'

  target 'Assign01_LoadingViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Assign01_LoadingViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
